# Generated by Django 5.0.1 on 2024-01-31 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre_alter_bookdetail_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='book_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='books.book'),
        ),
    ]
