# Generated by Django 5.0.1 on 2024-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_status_book_in_library_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
