# Generated by Django 5.0.1 on 2024-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_borrowedbook_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
